//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse200: Codable {

    public var search: [MovieOmdbapiObject]?
    public var totalResults: String?
    public var response: String?

    public init(search: [MovieOmdbapiObject]? = nil, totalResults: String? = nil, response: String? = nil) {
        self.search = search
        self.totalResults = totalResults
        self.response = response
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case search = "Search"
        case totalResults
        case response = "Response"
    }

}
