//
// MovieOmdbapiObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MovieOmdbapiObject: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case movie = "movie"
        case series = "series"
        case episode = "episode"
    }
    public var title: String?
    public var year: String?
    public var imdbID: String?
    public var type: ModelType?
    public var poster: String?

    public init(title: String? = nil, year: String? = nil, imdbID: String? = nil, type: ModelType? = nil, poster: String? = nil) {
        self.title = title
        self.year = year
        self.imdbID = imdbID
        self.type = type
        self.poster = poster
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title = "Title"
        case year = "Year"
        case imdbID
        case type = "Type"
        case poster = "Poster"
    }

}
