name: OmdbAPI
targets:
  OmdbAPI:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [OmdbAPI]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
